application: foo 
version: 1
runtime: go
api_version: go1
handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*)/
  static_files: \1/index.html
  upload: .*/index\.html
- url: /
  static_dir: .
pagespeed:
  enabled_rewriters:
  - MinifyCss
  - InlineJs
  - InlineImages
  - CollapseWhitespace
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls
